"""Tool: run Yosys synthesis and capture output/metrics.

Supports two execution modes (matching openroad_runner):
  - "local":  subprocess on this machine
  - "ray":    submit to a remote Ray-on-K8s cluster

The mode is controlled by ``OPENROAD_EXEC_MODE`` env var.
"""

from __future__ import annotations

import json
import os
import re
import subprocess
import time
from pathlib import Path

from langchain_core.tools import tool

from openroad_agent.config import OpenROADConfig
from openroad_agent.tools.session_manager import (
    get_session_name,
    register_current_run,
    resolve_run_dir,
)


# ── lazy config ────────────────────────────────────────────────────────
_cfg_instance: OpenROADConfig | None = None


def _get_cfg() -> OpenROADConfig:
    global _cfg_instance
    if _cfg_instance is None:
        _cfg_instance = OpenROADConfig()
    return _cfg_instance


# ── Default Yosys synthesis script template ────────────────────────────
# This is a self-contained Yosys TCL script that performs a complete
# RTL → gate-level netlist synthesis targeting a Liberty cell library.
# It mirrors the key steps from OpenROAD-flow-scripts/flow/scripts/synth*.tcl
# but is self-contained (no external env vars required beyond what we set).

YOSYS_SYNTH_TEMPLATE = r"""# ================================================================
# Yosys Synthesis Script  (auto-generated by openroad_agent)
# Design : {design_name}
# Top    : {top_module}
# Platform: {platform}
# ================================================================
yosys -import

# ── Read Liberty for cell mapping ──────────────────────────
{read_liberty_cmds}

# ── Read Verilog source(s) ─────────────────────────────────
{read_verilog_cmds}

# ── Synthesis ──────────────────────────────────────────────
hierarchy -check -top {top_module}
{synth_args_line}

# ── Technology mapping ─────────────────────────────────────
# Flip-flop mapping
dfflibmap -liberty {liberty_for_abc}

# Combinational mapping via ABC
{abc_line}

# ── Cleanup ────────────────────────────────────────────────
opt -purge
setundef -zero
splitnets
opt_clean -purge

{tiehi_tielo_cmds}
{insbuf_cmd}

# ── Reports ────────────────────────────────────────────────
tee -o {reports_dir}/synth_check.txt check
tee -o {reports_dir}/synth_stat.txt stat {stat_liberty_args}

# ── Write output ───────────────────────────────────────────
write_verilog -noattr -noexpr -nohex -nodec {output_verilog}
"""

# ── Platform-specific synthesis parameters ─────────────────────────────
# Minimal set of params needed for Yosys synthesis per supported platform.

_PLATFORM_SYNTH_PARAMS: dict[str, dict] = {
    "nangate45": {
        "liberty_files": ["Nangate45/Nangate45_typ.lib"],
        "dont_use_cells": ["TAPCELL_X1", "FILLCELL_X1", "AOI211_X1", "OAI211_X1"],
        "tiehi_cell_and_port": "LOGIC1_X1 Z",
        "tielo_cell_and_port": "LOGIC0_X1 Z",
        "min_buf_cell_and_ports": "BUF_X1 A Z",
        "abc_driver_cell": "BUF_X1",
        "abc_load_ff": "3.898",
        "latch_map": "",
        "clkgate_map": "",
        "adder_map": "",
    },
    "sky130hd": {
        "liberty_files": ["sky130hd/sky130_fd_sc_hd__tt_025C_1v80.lib"],
        "dont_use_cells": [
            "sky130_fd_sc_hd__probe_p_8",
            "sky130_fd_sc_hd__probec_p_8",
        ],
        "tiehi_cell_and_port": "sky130_fd_sc_hd__conb_1 HI",
        "tielo_cell_and_port": "sky130_fd_sc_hd__conb_1 LO",
        "min_buf_cell_and_ports": "sky130_fd_sc_hd__buf_4 A X",
        "abc_driver_cell": "sky130_fd_sc_hd__buf_1",
        "abc_load_ff": "5",
        "latch_map": "",
        "clkgate_map": "",
        "adder_map": "",
    },
    "sky130hs": {
        "liberty_files": ["sky130hs/sky130_fd_sc_hs__tt_025C_1v80.lib"],
        "dont_use_cells": [],
        "tiehi_cell_and_port": "sky130_fd_sc_hs__conb_1 HI",
        "tielo_cell_and_port": "sky130_fd_sc_hs__conb_1 LO",
        "min_buf_cell_and_ports": "sky130_fd_sc_hs__buf_4 A X",
        "abc_driver_cell": "sky130_fd_sc_hs__buf_1",
        "abc_load_ff": "5",
        "latch_map": "",
        "clkgate_map": "",
        "adder_map": "",
    },
    "asap7": {
        "liberty_files": [
            "asap7/asap7sc7p5t_SEQ_RVT_FF_nldm_220123.lib",
        ],
        "dont_use_cells": [],
        "tiehi_cell_and_port": "TIEHIx1_ASAP7_75t_R H",
        "tielo_cell_and_port": "TIELOx1_ASAP7_75t_R L",
        "min_buf_cell_and_ports": "BUFx2_ASAP7_75t_R A Y",
        "abc_driver_cell": "BUFx2_ASAP7_75t_R",
        "abc_load_ff": "1.0",
        "latch_map": "",
        "clkgate_map": "",
        "adder_map": "",
    },
}


def _resolve_liberty_path(platform: str, lib_rel: str, base_dir: str) -> str:
    """Resolve a liberty file path.

    Returns a relative path (relative to the test directory / CWD) so that it
    works on both local and remote execution where CWD is the test dir.
    """
    # Verify the file exists under base_dir
    candidate = os.path.join(base_dir, lib_rel)
    if os.path.isfile(candidate):
        return lib_rel          # keep relative — CWD is test_dir
    # Fallback: return as-is (rely on Yosys search path)
    return lib_rel


def build_yosys_synth_script(
    design_name: str,
    top_module: str,
    platform: str,
    verilog_files: list[str],
    output_verilog: str,
    reports_dir: str,
    *,
    liberty_files: list[str] | None = None,
    clock_period_ps: float | None = None,
    flatten: bool = True,
    abc_area: bool = False,
    extra_liberty_files: list[str] | None = None,
    dont_use_cells: list[str] | None = None,
    base_dir: str = "",
) -> str:
    """Build a complete Yosys synthesis TCL script.

    Args:
        design_name: Design name.
        top_module: Top-level Verilog module name.
        platform: Target PDK platform (nangate45, sky130hd, etc.).
        verilog_files: List of input Verilog/SystemVerilog file paths.
        output_verilog: Path for the synthesised gate-level netlist.
        reports_dir: Directory for synthesis reports.
        liberty_files: Override liberty file paths (if None, uses platform defaults).
        clock_period_ps: Clock period in ps for ABC timing-driven synthesis.
        flatten: Whether to flatten hierarchy during synthesis.
        abc_area: True = area-optimised ABC; False = speed-optimised (default).
        extra_liberty_files: Additional liberty files for mapping.
        dont_use_cells: Cells to exclude from mapping.
        base_dir: Base directory for resolving relative paths.

    Returns:
        Complete Yosys TCL script as a string.
    """
    params = _PLATFORM_SYNTH_PARAMS.get(platform)
    if params is None:
        raise ValueError(
            f"Unsupported platform '{platform}' for synthesis. "
            f"Supported: {list(_PLATFORM_SYNTH_PARAMS)}"
        )

    # Liberty files
    libs = liberty_files or [
        _resolve_liberty_path(platform, lf, base_dir) for lf in params["liberty_files"]
    ]
    if extra_liberty_files:
        libs.extend(extra_liberty_files)

    read_liberty_cmds = "\n".join(f'read_liberty -lib {lib}' for lib in libs)

    # Liberty for ABC (only first if multiple)
    liberty_for_abc = libs[0]

    # Stat liberty args
    stat_liberty_args = " ".join(f"-liberty {lib}" for lib in libs)

    # Verilog read commands
    read_verilog_cmds = "\n".join(
        f"read_verilog -sv {vf}" for vf in verilog_files
    )

    # Synth args
    synth_flags = f"-top {top_module}"
    if flatten:
        synth_flags += " -flatten"
    synth_args_line = f"synth {synth_flags}"

    # ABC line
    du_cells = dont_use_cells if dont_use_cells is not None else params.get("dont_use_cells", [])
    abc_dont_use = " ".join(f"-dont_use {c}" for c in du_cells) if du_cells else ""

    abc_cmd = "abc"
    if abc_area:
        abc_cmd += " -dff -D 1"  # area-optimised
    elif clock_period_ps:
        abc_cmd += f" -D {clock_period_ps}"

    abc_cmd += f" -liberty {liberty_for_abc}"
    if abc_dont_use:
        abc_cmd += f" {abc_dont_use}"
    abc_line = abc_cmd

    # Tie-hi / tie-lo mapping
    tiehi = params.get("tiehi_cell_and_port", "")
    tielo = params.get("tielo_cell_and_port", "")
    tiehi_tielo_cmds = ""
    if tiehi and tielo:
        tiehi_tielo_cmds = (
            f"hilomap -singleton \\\n"
            f"        -hicell {tiehi} \\\n"
            f"        -locell {tielo}"
        )

    # Buffer insertion
    min_buf = params.get("min_buf_cell_and_ports", "")
    insbuf_cmd = f"insbuf -buf {min_buf}" if min_buf else ""

    return YOSYS_SYNTH_TEMPLATE.format(
        design_name=design_name,
        top_module=top_module,
        platform=platform,
        read_liberty_cmds=read_liberty_cmds,
        read_verilog_cmds=read_verilog_cmds,
        synth_args_line=synth_args_line,
        liberty_for_abc=liberty_for_abc,
        abc_line=abc_line,
        tiehi_tielo_cmds=tiehi_tielo_cmds,
        insbuf_cmd=insbuf_cmd,
        reports_dir=reports_dir,
        stat_liberty_args=stat_liberty_args,
        output_verilog=output_verilog,
    )


# ── Metrics parsing from Yosys output ─────────────────────────────────

def _parse_yosys_metrics(stdout: str) -> dict:
    """Extract synthesis metrics from Yosys stdout."""
    metrics: dict = {}

    # Number of cells by type
    m = re.search(r'Number of cells:\s+(\d+)', stdout)
    if m:
        metrics["num_cells"] = int(m.group(1))

    # Number of wires
    m = re.search(r'Number of wires:\s+(\d+)', stdout)
    if m:
        metrics["num_wires"] = int(m.group(1))

    # Chip area (from stat)
    m = re.search(r'Chip area for (?:module|top module).*?:\s+([\d.]+)', stdout)
    if m:
        metrics["chip_area"] = float(m.group(1))

    # Alternative area format: "Estimated number of transistors..."
    m = re.search(r'Estimated number of transistors:\s+(\d+)', stdout)
    if m:
        metrics["estimated_transistors"] = int(m.group(1))

    # Cell counts by category from stat output
    for pattern, key in [
        (r'\$_DFF_\w+_\s+(\d+)', "num_flipflops"),
        (r'\$_SDFF_\w+_\s+(\d+)', "num_flipflops_sdff"),
        (r'\$_MUX_\s+(\d+)', "num_muxes"),
    ]:
        matches = re.findall(pattern, stdout)
        if matches:
            metrics[key] = sum(int(x) for x in matches)

    # Total number of library cells mapped (after techmap)
    m = re.search(r'Number of cells:\s+(\d+)', stdout)
    if m:
        metrics["num_cells"] = int(m.group(1))

    # Area from stat -liberty
    for m_iter in re.finditer(r'Chip area for (?:module|top module)\s+[^\s:]+\s*:\s*([\d.]+)', stdout):
        metrics["chip_area"] = float(m_iter.group(1))

    return metrics


def _fix_write_verilog_paths(script: str) -> str:
    """Ensure ``write_verilog`` outputs go into __RESULTS_DIR__.

    If the LLM produces a bare filename (no directory prefix) in a
    ``write_verilog`` command, the output would end up in the CWD
    (the OpenROAD test directory) instead of the run's results dir.
    This helper rewrites bare paths to ``__RESULTS_DIR__/<filename>``.
    """
    fixed_lines: list[str] = []
    for line in script.split("\n"):
        stripped = line.strip()
        # Match: write_verilog [options...] <path>
        m = re.match(
            r'^(write_verilog\s+(?:[-\w]+\s+)*)'   # command + flags
            r'(\S+)\s*$',                           # output path
            stripped,
        )
        if m:
            prefix, path = m.group(1), m.group(2)
            # If the path is a bare filename (no dir separator, no placeholder)
            if ("/" not in path
                    and "__RESULTS_DIR__" not in path
                    and "__REPORTS_DIR__" not in path
                    and not path.startswith("$")):
                fixed_lines.append(f"{prefix}__RESULTS_DIR__/{path}")
                continue
        fixed_lines.append(line)
    return "\n".join(fixed_lines)


# ── Local Yosys execution ─────────────────────────────────────────────

def _run_yosys_locally(
    cfg: OpenROADConfig,
    synth_script: str,
    run_label: str,
    timeout_seconds: int,
) -> str:
    """Run Yosys synthesis as a local subprocess."""
    run_dir = resolve_run_dir(cfg.work_dir, run_label)

    reports_dir = os.path.join(run_dir, "reports")
    os.makedirs(reports_dir, exist_ok=True)

    results_dir = os.path.join(run_dir, "results")
    os.makedirs(results_dir, exist_ok=True)

    # Substitute path placeholders in the script
    synth_script = synth_script.replace("__REPORTS_DIR__", reports_dir)
    synth_script = synth_script.replace("__RESULTS_DIR__", results_dir)

    tcl_path = os.path.abspath(os.path.join(run_dir, f"{run_label}.ys"))
    with open(tcl_path, "w") as f:
        f.write(synth_script)

    # Run yosys -c <script>
    cmd = [cfg.yosys_bin, "-c", tcl_path]

    t0 = time.time()
    try:
        proc = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=timeout_seconds,
            cwd=cfg.test_dir,
        )
        elapsed = time.time() - t0
        success = proc.returncode == 0
        full_stdout = proc.stdout
        full_stderr = proc.stderr
    except subprocess.TimeoutExpired:
        elapsed = time.time() - t0
        result = {
            "success": False,
            "stdout": "",
            "stderr": f"Yosys timeout after {timeout_seconds}s",
            "metrics": {},
            "elapsed_s": round(elapsed, 2),
            "result_files": [],
            "run_dir": os.path.abspath(run_dir),
            "remote": False,
            "tool": "yosys",
        }
        register_current_run(run_label, "yosys", result)
        return json.dumps(result)

    # Persist logs
    log_file = os.path.join(run_dir, f"{run_label}.log")
    with open(log_file, "w") as lf:
        lf.write(full_stdout)
    if full_stderr:
        stderr_log = os.path.join(run_dir, f"{run_label}.stderr.log")
        with open(stderr_log, "w") as lf:
            lf.write(full_stderr)

    # Truncate for JSON
    stdout = full_stdout[-8000:] if len(full_stdout) > 8000 else full_stdout
    stderr = full_stderr[-4000:] if len(full_stderr) > 4000 else full_stderr

    # Collect result files
    result_files = []
    for d in [results_dir, reports_dir]:
        if os.path.isdir(d):
            for fname in os.listdir(d):
                result_files.append(os.path.join(d, fname))

    metrics = _parse_yosys_metrics(full_stdout)

    result = {
        "success": success,
        "stdout": stdout,
        "stderr": stderr,
        "metrics": metrics,
        "elapsed_s": round(elapsed, 2),
        "result_files": result_files,
        "script_path": tcl_path,
        "log_file": log_file,
        "run_dir": os.path.abspath(run_dir),
        "remote": False,
        "tool": "yosys",
    }
    register_current_run(run_label, "yosys", result)
    return json.dumps(result)


# ── Ray remote Yosys execution ────────────────────────────────────────

def _run_yosys_via_ray(
    cfg: OpenROADConfig,
    synth_script: str,
    run_label: str,
    timeout_seconds: int,
) -> str:
    """Submit a Yosys synthesis job to the Ray cluster."""
    from openroad_agent.tools.ray_executor import run_yosys_on_ray

    # Collect local source files referenced in the script so they can be
    # uploaded to the remote cluster.  We look for ``read_verilog`` lines
    # that reference absolute local paths.
    source_files: dict[str, str] = {}   # {basename: content}
    lines = synth_script.split("\n")
    new_lines: list[str] = []
    for line in lines:
        m = re.match(r'^(read_verilog\s+(?:-sv\s+)?)(\S+)', line.strip())
        if m and os.path.isabs(m.group(2)):
            local_path = m.group(2)
            if os.path.isfile(local_path):
                basename = os.path.basename(local_path)
                with open(local_path, "r") as f:
                    source_files[basename] = f.read()
                # Replace with placeholder — remote task writes to __SRC_DIR__/<basename>
                new_lines.append(f"{m.group(1)}__SRC_DIR__/{basename}")
            else:
                new_lines.append(line)
        else:
            new_lines.append(line)
    synth_script = "\n".join(new_lines)

    result = run_yosys_on_ray(
        synth_script=synth_script,
        run_label=run_label,
        timeout_seconds=timeout_seconds,
        ray_address=cfg.ray_address,
        source_files=source_files,
        session_name=get_session_name(),
    )

    # Save local copies
    local_run_dir = resolve_run_dir(cfg.work_dir, run_label)
    local_script = os.path.join(local_run_dir, f"{run_label}.ys")
    with open(local_script, "w") as f:
        f.write(synth_script)

    log_content = result.pop("full_log", None) or result.get("stdout", "")
    if log_content:
        local_log = os.path.join(local_run_dir, f"{run_label}.log")
        with open(local_log, "w") as f:
            f.write(log_content)
        result["local_log"] = local_log
    result["local_run_dir"] = os.path.abspath(local_run_dir)

    # ── Sync remote results → local & push session meta → remote ──────
    from openroad_agent.tools.ray_executor import (
        sync_remote_run_to_local,
        push_session_meta_to_remote,
    )
    from openroad_agent.tools.session_manager import SessionManager

    remote_run_dir = result.get("run_dir", "")
    if remote_run_dir:
        synced = sync_remote_run_to_local(
            remote_run_dir, local_run_dir, cfg.ray_address,
            skip_dirs=["src"],
        )
        if synced:
            result["synced_files"] = synced

    # Expose the netlist path so the LLM can reference it directly.
    # Check remote result_files first, then fall back to local.
    for rf in result.get("result_files", []):
        if rf.endswith(".v"):
            result["synth_netlist_remote"] = rf
            local_netlist = os.path.join(
                local_run_dir, os.path.relpath(rf, remote_run_dir)
            ) if remote_run_dir else ""
            if os.path.isfile(local_netlist):
                result["synth_netlist_local"] = local_netlist
            break

    session = SessionManager.get_current()
    if session:
        register_current_run(run_label, "yosys", result)
        push_session_meta_to_remote(
            session.base_dir, session.session_name, cfg.ray_address,
        )

    return json.dumps(result)


# ═══════════════════════════════════════════════════════════════════════
# LangChain Tools
# ═══════════════════════════════════════════════════════════════════════

@tool
def run_yosys_synthesis(
    synth_script: str,
    run_label: str = "synth",
    timeout_seconds: int = 1800,
) -> str:
    """Execute a Yosys synthesis TCL/command script and return results.

    Execution happens locally or on the remote Ray cluster depending on
    the ``OPENROAD_EXEC_MODE`` setting ("local" or "ray").

    Args:
        synth_script: Complete Yosys TCL/command script content.
        run_label: Short label for file naming.
        timeout_seconds: Max wall-clock seconds.

    Returns:
        JSON with keys: success, stdout, stderr, metrics, elapsed_s,
        result_files, run_dir, remote, tool ("yosys").
    """
    cfg = _get_cfg()

    # Fix literal escape sequences from LLM
    if '\\n' in synth_script:
        synth_script = synth_script.replace('\\n', '\n')
    if '\\t' in synth_script:
        synth_script = synth_script.replace('\\t', '\t')

    # Ensure any write_verilog with a bare filename goes into __RESULTS_DIR__
    # so the output lands in the run directory (not in the CWD).
    synth_script = _fix_write_verilog_paths(synth_script)

    if cfg.execution_mode == "ray":
        return _run_yosys_via_ray(cfg, synth_script, run_label, timeout_seconds)
    return _run_yosys_locally(cfg, synth_script, run_label, timeout_seconds)


@tool
def generate_yosys_synth_script(
    design_name: str,
    top_module: str,
    platform: str,
    verilog_files: list[str],
    output_verilog: str = "",
    clock_period_ps: float = 0,
    flatten: bool = True,
    abc_area: bool = False,
) -> str:
    """Generate a Yosys synthesis script for the given design and platform.

    This builds a ready-to-run Yosys TCL script that reads the RTL Verilog,
    synthesises it with ABC, maps to the target cell library, and writes
    a gate-level netlist.

    Args:
        design_name: Design name (e.g. "gcd").
        top_module: Top-level module name.
        platform: Target PDK ("nangate45", "sky130hd", "sky130hs", "asap7").
        verilog_files: List of Verilog source file paths (relative to test dir).
        output_verilog: Output netlist path (default: results/<design>_synth.v).
        clock_period_ps: Clock period in ps for timing-driven ABC (0 = disable).
        flatten: Flatten hierarchy during synthesis.
        abc_area: Use area-optimised ABC script.

    Returns:
        The generated Yosys synthesis script as a string.
    """
    cfg = _get_cfg()

    # Use placeholders — the runner will substitute the actual paths
    reports_dir = "__REPORTS_DIR__"
    results_dir = "__RESULTS_DIR__"

    if not output_verilog:
        output_verilog = f"{results_dir}/{design_name}_synth.v"
    elif "__RESULTS_DIR__" not in output_verilog and not os.path.isabs(output_verilog):
        # Bare filename like "riscv32i_synth.v" — must go into results dir
        # so that the remote runner can find it and sync it back.
        output_verilog = f"{results_dir}/{output_verilog}"

    script = build_yosys_synth_script(
        design_name=design_name,
        top_module=top_module,
        platform=platform,
        verilog_files=verilog_files,
        output_verilog=output_verilog,
        reports_dir=reports_dir,
        clock_period_ps=clock_period_ps if clock_period_ps > 0 else None,
        flatten=flatten,
        abc_area=abc_area,
        base_dir=cfg.test_dir,
    )
    return script


@tool
def list_synth_platforms() -> str:
    """List platforms supported for Yosys synthesis with their key params.

    Returns:
        JSON with platform names and synthesis parameters.
    """
    info = {}
    for plat, params in _PLATFORM_SYNTH_PARAMS.items():
        info[plat] = {
            "liberty_files": params["liberty_files"],
            "dont_use_cells": params["dont_use_cells"][:3],
            "tie_cells": f"{params['tiehi_cell_and_port']} / {params['tielo_cell_and_port']}",
        }
    return json.dumps(info, indent=2)
